name: wsc
recipe: pantheon
config:
  framework: wordpress
  site: wp-starter-composer
  id: 292562b2-4cd7-4035-8413-91a50cb8246b
  edge: false
  #cache: false
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  pma:
    - pma-wsc.lndo.site
tooling:
  push:
    description: Push only database to dev
    options:
      code:
        default: none
      files:
        default: none
      database:
        default: dev
  pull:
    description: Pull only database
    options:
      code:
        default: none
      files:
        default: none
      database:
        default: live
